# Generated by Django 2.0.7 on 2020-06-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banuser', '0003_auto_20200618_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneduser',
            name='ban_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
